spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: root
    password: root1234!!
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
aws:
  dynamodb:
    endpoint: http://localhost:8000
    accessKey: dummy
    secretKey: dummy
    region: us-west-2